import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{vue,ts}'
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#00134d',
        'on-primary': '#ffffff',
        'primary-container': '#00247d',
        'on-primary-container': '#7a91ec',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001552',
        'on-primary-fixed-variant': '#264096',
        'secondary': '#236391',
        'on-secondary': '#ffffff',
        'secondary-container': '#91c9fe',
        'on-secondary-container': '#0b5583',
        'secondary-fixed': '#cee5ff',
        'secondary-fixed-dim': '#96ccff',
        'on-secondary-fixed': '#001d32',
        'on-secondary-fixed-variant': '#004a75',
        'tertiary': '#3d0005',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#64000d',
        'on-tertiary-container': '#ff5f60',
        'tertiary-fixed': '#ffdad8',
        'tertiary-fixed-dim': '#ffb3af',
        'on-tertiary-fixed': '#410006',
        'on-tertiary-fixed-variant': '#930019',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
        'surface': '#f8f9fa',
        'on-surface': '#191c1d',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface-variant': '#444652',
        'outline': '#757683',
        'outline-variant': '#c5c5d4',
        'surface-tint': '#4158b0',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#b7c4ff',
      },
      fontFamily: {
        'display-lg': ['Archivo Narrow'],
        'headline-lg': ['Archivo Narrow'],
        'headline-md': ['Archivo Narrow'],
        'headline-sm': ['Archivo Narrow'],
        'title-md': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        'base': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '20px',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    }
  },
  plugins: []
} satisfies Config
