"""initial schema

Revision ID: 6397fc500673
Revises: 
Create Date: 2026-06-07 14:07:50.929641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6397fc500673'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('world_cup_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_cup_groups_name'), 'world_cup_groups', ['name'], unique=True)
    op.create_table('prediction_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('invite_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_groups_creator_id'), 'prediction_groups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_prediction_groups_invite_code'), 'prediction_groups', ['invite_code'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('world_cup_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_cup_group_id'], ['world_cup_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=True)
    op.create_index(op.f('ix_teams_world_cup_group_id'), 'teams', ['world_cup_group_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['prediction_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('group_prizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.CheckConstraint('rank BETWEEN 1 AND 3', name='ck_rank_1_3'),
    sa.ForeignKeyConstraint(['group_id'], ['prediction_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'rank', name='uq_group_rank')
    )
    op.create_index(op.f('ix_group_prizes_group_id'), 'group_prizes', ['group_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('world_cup_group_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=False),
    sa.Column('deadline_utc', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['world_cup_group_id'], ['world_cup_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_deadline_utc'), 'matches', ['deadline_utc'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_kickoff_utc'), 'matches', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_world_cup_group_id'), 'matches', ['world_cup_group_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.CheckConstraint('away_score >= 0', name='ck_away_score_gte_0'),
    sa.CheckConstraint('home_score >= 0', name='ck_home_score_gte_0'),
    sa.ForeignKeyConstraint(['group_id'], ['prediction_groups.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', 'group_id', name='uq_user_match_group')
    )
    op.create_index(op.f('ix_predictions_group_id'), 'predictions', ['group_id'], unique=False)
    op.create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('prediction_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('points IN (0, 1, 3)', name='ck_points_valid'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_scores_prediction_id'), 'prediction_scores', ['prediction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_scores_prediction_id'), table_name='prediction_scores')
    op.drop_table('prediction_scores')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_group_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_matches_world_cup_group_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_kickoff_utc'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_deadline_utc'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_group_prizes_group_id'), table_name='group_prizes')
    op.drop_table('group_prizes')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_teams_world_cup_group_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_prediction_groups_invite_code'), table_name='prediction_groups')
    op.drop_index(op.f('ix_prediction_groups_creator_id'), table_name='prediction_groups')
    op.drop_table('prediction_groups')
    op.drop_index(op.f('ix_world_cup_groups_name'), table_name='world_cup_groups')
    op.drop_table('world_cup_groups')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
