// Registers the service worker generated by vite-plugin-pwa.
// `registerType: 'autoUpdate'` means new SW versions activate as soon as they
// are downloaded, so callers do not need to prompt the user.
import { registerSW } from 'virtual:pwa-register'

export function registerServiceWorker(): void {
  // No-op outside of browsers (e.g. SSR, vitest happy-dom without SW support).
  if (typeof window === 'undefined') return

  registerSW({
    immediate: true,
    onRegisterError(error) {
      // Surface registration failures in dev/console without breaking the app.
      // eslint-disable-next-line no-console
      console.error('[pwa] service worker registration failed', error)
    }
  })
}
